version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: alumni_db
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'

volumes:
  db-data:
